# Generated by Django 3.1.4 on 2021-02-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210224_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='OUT', max_length=3),
            preserve_default=False,
        ),
    ]
