# Generated by Django 3.1.4 on 2021-02-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('FREE', 'FREE')], default='FREE', max_length=4),
        ),
    ]
