# Generated by Django 3.1.4 on 2021-03-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reflected',
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
