# Generated by Django 3.1.4 on 2021-03-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210315_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rfid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
